name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          xcode: [12.0]
          destination: ['platform=iOS Simulator,name=iPhone 11']
    steps:
      - run: swift --version
      - name: Checkout
        uses: actions/checkout@v2
      - name: Combine iOS Unit Tests
        id: test_ios_app
        run: |
          xcodebuild clean build test -project CombineStudy/CombineStudy.xcodeproj -scheme CombineStudy -destination "${destination}";
        env: 
          destination: ${{ matrix.destination }}
